### PR TITLE
Bump evercrypt to 0.0.4 (#6)

### LINKED ISSUE #6: Bump evercrypt to 0.0.4

### PR DESCRIPTION
**Pull request by sgmenda**
Closes #6

### CODE REVIEW

**Comment by sgmenda** [comment]
This would a step towards resolving: https://github.com/openmls/openmls/issues/246

**Comment by franziskuskiefer** [comment]
Thanks for the PR. Unfortunately this isn't enough to get Windows build working as you can see [here](https://github.com/franziskuskiefer/hpke-rs/runs/1412210880?check_suite_focus=true). I didn't get around to looking into what's going on. If you have a Windows machine and could fix the issue, this would be great.

**Comment by sgmenda** [comment]
Yup, I noticed that, I was gonna tackle that in a separate diff, but I can take a look on a Windows machine later today.

**Comment by sgmenda** [comment]
I can't seem to figure out what's wrong. Build fails on my local Windows machine with a different error:

```
  thread 'main' panicked at 'Failed to copy hacl-star to out_dir.: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', evercrypt-sys\build.rs:85:10
```

I tried replacing the arguments in the command with the full path (ie changed [this line](https://github.com/franziskuskiefer/evercrypt-rust/blob/master/evercrypt-sys/build.rs#L76)) and it still seems to fail.

Have you encountered this before?

**Comment by franziskuskiefer** [comment]
You have to get the visual studio tools in your path. This currently only works with 
[VS2019 Enterprise](https://github.com/franziskuskiefer/evercrypt-rust/blob/master/evercrypt-sys/hacl-build.bat). This should probably be changed to be a little more flexible. With the path set correctly you should get the same error you see in the logs.

**Comment by sgmenda** [comment]
Yup, I changed those lines in `hacl-build.bat` as mentioned in the `README.md`. This panic seems to be happening before the `hacl-build.bat` script is called in the `build.rs` in the `copy_hacl_to_out(&out_path, &hacl_src_path)` step.

More specifically, the panic seems to be triggering here: https://github.com/franziskuskiefer/evercrypt-rust/blob/master/evercrypt-sys/build.rs#L76

**Comment by franziskuskiefer** [comment]
Interesting. Sounds like the paths aren't correct. I suspect that the evercrypt-rust build currently can't handle being used as part of another build here on Windows.

**Comment by franziskuskiefer** [comment]
I pushed a "fix" to evercrypt and it works fine for me locally but not on CI...
@sgmenda can you test with the version currently on master?

**Comment by sgmenda** [comment]
Nope, still fails with the same error. :/

```
   Compiling evercrypt-sys v0.0.5 (C:\Users\sanke\Projects\CryptographyProjects\evercrypt-rust\evercrypt-sys)
error: failed to run custom build command for `evercrypt-sys v0.0.5 (C:\Users\sanke\Projects\CryptographyProjects\evercrypt-rust\evercrypt-sys)`

Caused by:
  process didn't exit successfully: `C:\Users\sanke\Projects\CryptographyProjects\evercrypt-rust\target\debug\build\evercrypt-sys-e5ced8dcb5e7d1a4\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=wrapper.h
  cargo:rerun-if-changed=hacl-star

  --- stderr
  thread 'main' panicked at 'Failed to copy hacl-star to out_dir.: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', evercrypt-sys\build.rs:79:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

At this point, it seems like an issue with my windows machine. Sorry about the inconvenience.

**Comment by franziskuskiefer** [comment]
No there was also an issue with the build. I fixed it on CI. Check out this branch https://github.com/franziskuskiefer/hpke-rs/tree/0.0.4

Note that it builds against [this branch](https://github.com/franziskuskiefer/evercrypt-rust/tree/0.0.6) of evercrypt that has the fix for the CI [here]. Note that there's currently no mechanism to easily change the VS version and you have to do it in the version cargo checks out for you. I'm not a Windows user so this is fine for me. If you want to make this more ergonomic feel free to file PRs for evercrypt.

**Comment by sgmenda** [comment]
For me, `hpke-rs` tag `v0.0.4` and indeed `evercrypt-rust` tag `v0.0.6` both seem to fail at the copy step. If it passes on CI, it seems like an issue with my machine. (Also, I recently moved to windows from linux, so I am not really sure how to debug issues like this. 😞)

```
   Compiling evercrypt-sys v0.0.6
error: failed to run custom build command for `evercrypt-sys v0.0.6`

Caused by:
  process didn't exit successfully: `C:\Users\sanke\Projects\CryptographyProjects\hpke-rs\target\debug\build\evercrypt-sys-63ece7b7df833f70\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=wrapper.h
  cargo:rerun-if-changed=hacl-star
  build_config: BuildConfig { hacl_src_dir: "msvc-compatible", cross: false, config_flags: [], make_flags: [], env: {}, lib_name: "libevercrypt", windows: true }
  out_path: "C:\\Users\\sanke\\Projects\\CryptographyProjects\\hpke-rs\\target\\debug\\build\\evercrypt-sys-4cfc6cfbb2798152\\out"
  hacl_src_path: "C:\\Users\\sanke\\Projects\\CryptographyProjects\\hpke-rs\\target\\debug\\build\\evercrypt-sys-4cfc6cfbb2798152\\out\\hacl-star\\dist\\msvc-compatible"

  --- stderr
  thread 'main' panicked at 'Failed to copy hacl-star to out_dir.: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', C:\Users\sanke\.cargo\registry\src\github.com-1ecc6299db9ec823\evercrypt-sys-0.0.6\build.rs:80:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
   Compiling evercrypt-sys v0.0.6 (C:\Users\sanke\Projects\CryptographyProjects\evercrypt-rust\evercrypt-sys)
error: failed to run custom build command for `evercrypt-sys v0.0.6 (C:\Users\sanke\Projects\CryptographyProjects\evercrypt-rust\evercrypt-sys)`

Caused by:
  process didn't exit successfully: `C:\Users\sanke\Projects\CryptographyProjects\evercrypt-rust\target\debug\build\evercrypt-sys-41721f1677740277\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=wrapper.h
  cargo:rerun-if-changed=hacl-star
  build_config: BuildConfig { hacl_src_dir: "msvc-compatible", cross: false, config_flags: [], make_flags: [], env: {}, lib_name: "libevercrypt", windows: true }
  out_path: "C:\\Users\\sanke\\Projects\\CryptographyProjects\\evercrypt-rust\\target\\debug\\build\\evercrypt-sys-a8f3f4792917b5f0\\out"
  hacl_src_path: "C:\\Users\\sanke\\Projects\\CryptographyProjects\\evercrypt-rust\\target\\debug\\build\\evercrypt-sys-a8f3f4792917b5f0\\out\\hacl-star\\dist\\msvc-compatible"

  --- stderr
  thread 'main' panicked at 'Failed to copy hacl-star to out_dir.: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', evercrypt-sys\build.rs:80:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by franziskuskiefer** [comment]
> 'Failed to copy hacl-star to out_dir.: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }'

Windows builds are always a little tricky. So this says it couldn't find the `hacl-star` directory to copy. Does `C:\Users\sanke\.cargo\registry\src\github.com-1ecc6299db9ec823\evercrypt-sys-0.0.6\hacl-star` exist? If not, the questions would be why, and if it exists, the question is why the build doesn't find it.

**Comment by sgmenda** [comment]
In https://github.com/franziskuskiefer/hpke-rs/pull/7#issuecomment-740313977 , I tried replacing the implicit path with the full path (cf. [the diff](https://gist.github.com/sgmenda/b6567f5bb742eb4ab6b97321351c9fc6)), print out the paths
```
  hacl_star_path: "C:\\Users\\sanke\\Projects\\CryptographyProjects\\evercrypt-rust\\evercrypt-sys\\hacl-star"
  out_dir: "C:\\Users\\sanke\\Projects\\CryptographyProjects\\evercrypt-rust\\target\\debug\\build\\evercrypt-sys-a8f3f4792917b5f0\\out"
```
and then tried manually to run the command
```
cp -r "C:\\Users\\sanke\\Projects\\CryptographyProjects\\evercrypt-rust\\evercrypt-sys\\hacl-star"  "C:\\Users\\sanke\\Projects\\CryptographyProjects\\evercrypt-rust\\target\\debug\\build\\evercrypt-sys-a8f3f4792917b5f0\\out"
```
and it succeeded. But the build script always seems to fail with the same error, even if I hardcode the paths. Unfortunately, I don't have a second Windows machine to reproduce this, and since the CI seems to works, it seems to strongly indicate that there is something wrong with my machine / rust config.

**Comment by franziskuskiefer** [comment]
> Unfortunately, I don't have a second Windows machine to reproduce this, and since the CI seems to works, it seems to strongly indicate that there is something wrong with my machine / rust config.

I'd be very interested to understand what's going on here. But without more information we're stuck.
I'll close this and issue #6. But please open another issue if you have more information on the problem.

**Pull request closed without merging**
